# ===========================================================================
# AUTO-GENERATED by phase2/auth/bootstrap.py (No Auth Mode)
# Last refreshed: 2026-04-22 11:33:18
# DO NOT edit manually - this file is overwritten on each token refresh.
# ===========================================================================

HEADERS = {
    "authorization": 'Bearer oauth2v2_int_2a1dfdc97387a52f854986e231042ae6',
    "user-agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
    "accept": "*/*",
    "content-type": "application/json",
    "x-upwork-api-tenantid": ''
}

COOKIES = {'cf_clearance': 'VB8vJjpxiT8UYIlD0r4nCbBnmNwOPydAqtUrgaAHHmM-1776839596-1.2.1.1-6XBTg_85xJAZwgQfgUZvojdP7PZtGgWPk3OYGuThdIHQrc9t7hO4s7VyISNil3fpPvJLhJjpdaVtRgbSqWMdwHyR6tHLqMlo7KhicizY2VFWsoQp3mU15aWPb6GY0Xh6dfUR8SmDRFzdHlIGQ.DBK4smy9yzquCAH0.eFZ3nB_uT82InuJoen5Yk2sc7b3WhXk.6_OsR6QEZlabgG5fc.89I4aSDgAkOcP3hPJhxkb6BFxFWlv4thVYL.Vs17ZTtIkoEbNp2W8hYGuWDNN5Jz14yKjt6ocpM8FdgXo00yAwVYxpkhXTOG1CFDS1EKk40vvNDy9CbVUTgWcb5GJH83g', 'visitor_id': '39.45.53.149.1776839596668000', 'enabled_ff': '!CI12577UniversalSearch,!CmpLibOn,!Fluid,!MP16400Air3Migration,!SSINavUser,!i18nGA,CI17409DarkModeUI,JPAir3,OTBnrOn,SSINavUserBpa,TONB2256Air3Migration,i18nOn', 'AWSALBTG': 'ehDEJ8icEMZkfUMSSsBDITY9EQQOtKMZClbFOAaZO4x74Gn++Ri3ObzHx4gc4o6x5Q2tFa0lcq+u8S7mMOwcYB+FYZZu7D6opySxkcBI9PlasrJ2BkGXsrRTPEfn+HgFqDtRWfz4d/zJ2TdSzRCO/fcxFNAxHkS4z3Rzu4hV+fph', 'AWSALBTGCORS': 'ehDEJ8icEMZkfUMSSsBDITY9EQQOtKMZClbFOAaZO4x74Gn++Ri3ObzHx4gc4o6x5Q2tFa0lcq+u8S7mMOwcYB+FYZZu7D6opySxkcBI9PlasrJ2BkGXsrRTPEfn+HgFqDtRWfz4d/zJ2TdSzRCO/fcxFNAxHkS4z3Rzu4hV+fph', 'UniversalSearchNuxt_vt': 'oauth2v2_int_2a1dfdc97387a52f854986e231042ae6', 'country_code': 'PK', 'cookie_prefix': '', 'cookie_domain': '.upwork.com', '__cflb': '02DiuEXPXZVk436fJfSVuuwDqLqkhavJb4hgCvER4mXYP', 'x-spec-id': 'a4ef58a3-98a3-4ff8-80f4-a83bfffb6071', '_cfuvid': 'lZOZrFaLRQ0TTXVPQWFlYzYxfX649wKUVP771unxq5o-1776839596.5161128-1.0.1.1-pAk9l26mqh4r0ZnAjYmZFfOZ1lcnt7_HnQA8IxQl5sQ', '__cf_bm': 'oTjsbn4GZXtfCfOzCCDdDX1lcY94MJ6S_V6o3EUuAkI-1776839597.8006809-1.0.1.1-wwRG.sF4TB0MCJEm4E6PlPOAMvsd94oMUnXlEI6HKQyMTGiJCqyy95_GvBmqC8YO.9iQ7YAFzSwVl6qWZjVG9g7_f5FiLhcobMYk.bYpKTHL4UTw8JLAM2IVFAisxIH0', 'umq': '1280'}
