"""
Cloudflare Bypass Solver — SeleniumBase UC Mode
================================================
Runs in headless2 mode.
Uses page_load_strategy="none" to prevent driver deadlocks.
Extracts cf_clearance cookies and Bearer token, saves to config.py.
"""

import sys
import json
import time
import logging
from pathlib import Path

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ── Paths ──
BASE_DIR    = Path(__file__).resolve().parent              # cloudflare/bypass/
ROOT_DIR    = BASE_DIR.parent.parent                       # Discord Bot/
CONFIG_PATH = ROOT_DIR / "scraper" / "core" / "config.py"
SESSION_PATH = ROOT_DIR / "scraper" / "core" / "session.json"
SEARCH_URL  = "https://www.upwork.com/nx/search/jobs/?q=python"

# We use a dedicated logger for the solver that also prints to stdout
logger = logging.getLogger("solver")
logger.setLevel(logging.INFO)
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(logging.Formatter('[%(asctime)s] [%(levelname)-8s] %(message)s', '%Y-%m-%d %H:%M:%S'))
logger.addHandler(handler)

def _write_config(token: str, cookies: list, user_agent: str):
    cookie_dict = {c["name"]: c["value"] for c in cookies}
    timestamp   = time.strftime("%Y-%m-%d %H:%M:%S")
    auth_value  = f"Bearer {token}" if not token.startswith("Bearer ") else token

    # 1. Update config.py (Python backup)
    content = f'''# ===========================================================================
# AUTO-GENERATED by cloudflare/bypass/solver.py
# Last refreshed: {timestamp}
# ===========================================================================

HEADERS = {{
    "authorization": {repr(auth_value)},
    "user-agent":    {repr(user_agent)},
    "accept":        "*/*",
    "content-type":  "application/json",
    "x-upwork-api-tenantid": ""
}}

COOKIES = {repr(cookie_dict)}
'''
    CONFIG_PATH.write_text(content, encoding="utf-8")
    
    # 2. Update session.json (Professional standard)
    session_data = {
        "headers": {
            "authorization": auth_value,
            "user-agent": user_agent,
            "accept": "*/*",
            "content-type": "application/json",
            "x-upwork-api-tenantid": ""
        },
        "cookies": cookie_dict,
        "updated_at": timestamp
    }
    with open(SESSION_PATH, "w", encoding="utf-8") as f:
        json.dump(session_data, f, indent=2)

    logger.info(f"Session files updated:")
    logger.info(f"  -> {CONFIG_PATH.name}")
    logger.info(f"  -> {SESSION_PATH.name}")
    logger.info(f"Authorization: {auth_value[:60]}...")
    logger.info(f"Cookies extracted: {len(cookie_dict)}")

def solve_cloudflare(max_retries=3):
    from seleniumbase import SB

    logger.info("=" * 60)
    logger.info("  UPWORK AUTH SOLVER — SeleniumBase UC (Headless2)")
    logger.info("=" * 60)

    success = False

    for attempt in range(1, max_retries + 1):
        logger.info(f"Attempt {attempt}/{max_retries}...")

        try:
            # We use page_load_strategy="none" because Cloudflare Turnstile blocks
            # the page load event in headless mode, which causes get_cookies() to deadlock.
            with SB(uc=True, headless2=True, incognito=True, page_load_strategy="none") as sb:
                
                logger.info("Opening Upwork...")
                # Reconnect strips the headless webdriver fingerprint
                sb.uc_open_with_reconnect(SEARCH_URL, reconnect_time=6)

                logger.info("Waiting 15 s for Cloudflare to resolve...")
                time.sleep(15)

                logger.info("Extracting cookies...")
                raw = sb.driver.get_cookies()

                ua = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/120.0.0.0 Safari/537.36")

                cookies = [{"name": c["name"], "value": c["value"]} for c in raw]
                token   = next((c["value"] for c in raw if c["name"] == "UniversalSearchNuxt_vt"), "")
                cf_ok   = any(c["name"] == "cf_clearance" for c in raw)

                logger.info(f"Cookies: {len(cookies)} | cf_clearance: {cf_ok} | token: {bool(token)}")

                if token and cf_ok:
                    _write_config(token, cookies, ua)
                    success = True
                    logger.info("Cloudflare bypass successful.")
                    try:
                        sb.driver.quit()
                    except Exception:
                        pass
                    import os; os._exit(0)
                else:
                    logger.warning(f"Attempt {attempt}: missing token or cf_clearance.")

        except Exception as e:
            logger.error(f"Attempt {attempt} error: {e}")

        if attempt < max_retries:
            logger.info("Retrying in 3 s...")
            time.sleep(3)

    if not success:
        logger.error("All attempts exhausted. Tokens not updated.")
        sys.exit(1)

if __name__ == "__main__":
    solve_cloudflare()
