import asyncio
import json
import sys
import time
from pathlib import Path
from playwright.async_api import async_playwright

# Fix Windows terminal encoding (PowerShell default is cp1252)
if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Paths
BASE_DIR        = Path(__file__).resolve().parent          # phase2/auth/
PHASE2_DIR      = BASE_DIR.parent                          # phase2/
PHASE1_DIR      = PHASE2_DIR.parent / "phase1"             # phase1/
CONFIG_PATH     = PHASE1_DIR / "scraper" / "config.py"
COOKIES_PATH    = BASE_DIR / "cookies.json"

SEARCH_URL      = "https://www.upwork.com/nx/search/jobs/?q=python"
GRAPHQL_URL     = "https://www.upwork.com/api/graphql/v1"

def _write_config(headers: dict, cookies: list, user_agent: str):
    cookie_dict = {c["name"]: c["value"] for c in cookies}
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

    config_content = f'''# ===========================================================================
# AUTO-GENERATED by phase2/auth/bootstrap.py (No Auth Mode)
# Last refreshed: {timestamp}
# DO NOT edit manually - this file is overwritten on each token refresh.
# ===========================================================================

HEADERS = {{
    "authorization": {repr(headers.get("authorization", ""))},
    "user-agent": {repr(user_agent)},
    "accept": "*/*",
    "content-type": "application/json",
    "x-upwork-api-tenantid": {repr(headers.get("x-upwork-api-tenantid", ""))}
}}

COOKIES = {repr(cookie_dict)}
'''

    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(config_content)

    print(f"[OK] config.py updated -> {CONFIG_PATH}")
    print(f"     Authorization: {headers.get('authorization', 'NOT FOUND')[:60]}...")
    print(f"     Total cookies written: {len(cookie_dict)}")

async def _intercept_graphql(page):
    captured = {}
    captured_event = asyncio.Event()

    async def handle_request(request):
        if GRAPHQL_URL in request.url:
            all_headers = request.headers
            for key, value in all_headers.items():
                if key.lower() in {"authorization", "x-upwork-api-tenantid"}:
                    captured[key.lower()] = value
            if "authorization" in captured:
                captured_event.set()

    page.on("request", handle_request)
    
    print("[*] Opening Upwork public search page to solve Cloudflare and grab Visitor Token...")
    await page.goto(SEARCH_URL, wait_until="domcontentloaded", timeout=60000)
    
    # Trigger a 2nd page to force a GraphQL XHR payload if the first load didn't do it
    if not captured_event.is_set():
        print("[*] Simulating scroll & next page click to trigger GraphQL...")
        await page.evaluate("window.scrollBy(0, 1000)")
        await asyncio.sleep(2)
        await page.goto(SEARCH_URL + "&page=2", wait_until="domcontentloaded", timeout=60000)

    try:
        await asyncio.wait_for(captured_event.wait(), timeout=15)
        print("[OK] Authorization header captured!")
    except asyncio.TimeoutError:
        print("[!] Warning: Authorization header was NOT captured.")
        
    return captured

async def bootstrap():
    """
    Main bootstrap function: Zero-Login Cloudflare Bypass.
    """
    print("\n" + "=" * 60)
    print("  UPWORK AUTH BOOTSTRAP - Phase 2 (No Auth / CF Bypass)")
    print("=" * 60)

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            slow_mo=50,
            args=[
                "--start-maximized",
                "--disable-blink-features=AutomationControlled",
            ]
        )

        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            locale="en-US",
            timezone_id="America/New_York",
        )

        await context.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
        )

        page = await context.new_page()

        captured_headers = await _intercept_graphql(page)

        print("[*] Extracting cookies and User-Agent...")
        cookies = await context.cookies()
        user_agent = await page.evaluate("navigator.userAgent")
        
        # Save cache for Phase 2's own sanity logic optionally
        with open(COOKIES_PATH, "w", encoding="utf-8") as f:
            json.dump(cookies, f, indent=2)
        print(f"[OK] {len(cookies)} cookies saved -> {COOKIES_PATH}")

        # Overwrite Phase 1 config.py
        _write_config(captured_headers, cookies, user_agent)

        print("\n[OK] Phase 2 Bootstrap complete. Closing browser...\n")
        await browser.close()

if __name__ == "__main__":
    asyncio.run(bootstrap())
